name: RELEASE

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build-front:
    name: Build Front
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['12.14']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./ergoMixFront

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dep and Build
        run: |
          npm install
          CI=false npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: front-build
          path: ./ergoMixFront/build/*
          retention-days: 1
          if-no-files-found: error
